version: '3'

services:

  db:
    image: postgres:9.6
    restart: on-failure
    environment:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pguser
          POSTGRES_DB: appdb
    ports:
       - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
