version: '3'

services:

  db:
    image: postgres:9.6
    restart: on-failure
    environment:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: appdb
    ports:
       - 5432:5432
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
