server:
  port: 3001
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:yunar;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: testuser
    password: testpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:h2:mem:yunar;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    user: testuser
    password: testpassword
    schemas: PUBLIC
    baseline-on-migrate: true