server:
  port: 3001
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/appdb
    username: testuser
    password: testpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    url: jdbc:postgresql://localhost/appdb
    user: testuser
    password: testpassword